{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d721bc79-00f1-48f2-8f51-e80cad3a8001",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-11 14:56:09,423 - __main__ - INFO - Bot main function scheduled as a task on existing event loop.\n",
      "2025-06-11 14:56:10,497 - __main__ - INFO - Messages from sheet have changed or are new. Resetting current_message_index to 0.\n",
      "2025-06-11 14:56:10,498 - __main__ - INFO - Successfully loaded 3 messages from Google Sheet.\n",
      "2025-06-11 14:56:10,559 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts\n",
      "2025-06-11 14:56:10,559 - __main__ - INFO - Scheduled job: daily_message_10_29 for 10:29 Europe/Moscow\n",
      "2025-06-11 14:56:10,559 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts\n",
      "2025-06-11 14:56:10,559 - __main__ - INFO - Scheduled job: daily_message_10_30 for 10:30 Europe/Moscow\n",
      "2025-06-11 14:56:10,560 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts\n",
      "2025-06-11 14:56:10,560 - __main__ - INFO - Scheduled job: daily_message_10_31 for 10:31 Europe/Moscow\n",
      "2025-06-11 14:56:10,560 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts\n",
      "2025-06-11 14:56:10,560 - __main__ - INFO - Scheduled job: daily_message_10_32 for 10:32 Europe/Moscow\n",
      "2025-06-11 14:56:10,560 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts\n",
      "2025-06-11 14:56:10,560 - __main__ - INFO - Scheduled job: reload_sheet_messages every 6 hours.\n",
      "2025-06-11 14:56:10,561 - apscheduler.scheduler - INFO - Added job \"Send message at 10:29 Moscow time\" to job store \"default\"\n",
      "2025-06-11 14:56:10,561 - apscheduler.scheduler - INFO - Added job \"Send message at 10:30 Moscow time\" to job store \"default\"\n",
      "2025-06-11 14:56:10,561 - apscheduler.scheduler - INFO - Added job \"Send message at 10:31 Moscow time\" to job store \"default\"\n",
      "2025-06-11 14:56:10,561 - apscheduler.scheduler - INFO - Added job \"Send message at 10:32 Moscow time\" to job store \"default\"\n",
      "2025-06-11 14:56:10,561 - apscheduler.scheduler - INFO - Added job \"Reload messages from Google Sheet every 6 hours\" to job store \"default\"\n",
      "2025-06-11 14:56:10,562 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2025-06-11 14:56:10,562 - __main__ - INFO - Bot started. Press Ctrl+C to stop.\n"
     ]
    }
   ],
   "source": [
    "import logging\n",
    "import requests\n",
    "import pandas as pd\n",
    "from telegram import Update\n",
    "from telegram.ext import Application, CommandHandler, ContextTypes\n",
    "from apscheduler.schedulers.asyncio import AsyncIOScheduler\n",
    "from apscheduler.triggers.cron import CronTrigger\n",
    "from apscheduler.triggers.interval import IntervalTrigger\n",
    "import pytz\n",
    "import os\n",
    "import asyncio\n",
    "\n",
    "# === CONFIGURATION ===\n",
    "# IMPORTANT: Replace \"7818282877:AAFEuuksW8xjH111cRFOv2iTm8bZjqjpWh4\" and \"-1002850808376\"\n",
    "# with your actual bot token and channel ID obtained from BotFather.\n",
    "# Using environment variables is recommended for production (as shown with os.environ.get).\n",
    "BOT_TOKEN = os.environ.get(\"TELEGRAM_BOT_TOKEN\", \"7818282877:AAFEuuksW8xjH111cRFOv2iTm8bZjqjpWh4\")\n",
    "CHANNEL_ID = os.environ.get(\"TELEGRAM_CHANNEL_ID\", \"-1002850808376\")\n",
    "\n",
    "# URL of your Google Sheet exported as CSV (make sure it's publicly accessible)\n",
    "SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/1LY8Gv6ZTn0XGEiFxmSy5AU9CVv7F6CnArZeTCKIVCh4/export?format=csv&gid=0'\n",
    "\n",
    "# Define the timezone for your scheduled messages\n",
    "MOSCOW_TIMEZONE = 'Europe/Moscow'\n",
    "\n",
    "# Define the specific times (hour, minute) to send messages in Moscow time.\n",
    "# You can easily add, remove, or change times here.\n",
    "# Example: (hour_24_format, minute_0_to_59)\n",
    "SCHEDULED_TIMES_MOSCOW = [\n",
    "    (10, 29),    # 10:21 Moscow time\n",
    "    (10, 30),    # 10:22 Moscow time\n",
    "    (10, 31),    # 10:23 Moscow time\n",
    "    (10, 32)     # 10:24 Moscow time\n",
    "]\n",
    "\n",
    "# NEW CONFIGURATION: How often to reload messages from the Google Sheet (in hours)\n",
    "SHEET_RELOAD_INTERVAL_HOURS = 6 # Reload messages every 6 hours\n",
    "\n",
    "# === LOGGING SETUP ===\n",
    "logging.basicConfig(\n",
    "    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n",
    "    level=logging.INFO\n",
    ")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "# === GLOBAL VARIABLES (for storing messages and current index) ===\n",
    "# In a production environment, you'd want to persist 'all_messages' and\n",
    "# 'current_message_index' in a database to survive bot restarts.\n",
    "all_messages = []\n",
    "current_message_index = 0\n",
    "\n",
    "# === HELPER FUNCTION: CONVERT GOOGLE DRIVE LINK TO DIRECT LINK ===\n",
    "def convert_drive_link(link):\n",
    "    \"\"\"Converts a shareable Google Drive link to a direct download/view link.\"\"\"\n",
    "    if isinstance(link, str) and \"drive.google.com\" in link:\n",
    "        parts = link.split('/')\n",
    "        try:\n",
    "            file_id_index = parts.index('d') + 1\n",
    "            file_id = parts[file_id_index]\n",
    "            return f\"https://drive.google.com/uc?export=view&id={file_id}\"\n",
    "        except (ValueError, IndexError):\n",
    "            logger.warning(f\"Could not parse Google Drive link: {link}\")\n",
    "            return None\n",
    "    return link\n",
    "\n",
    "# === DATA LOADING: LOAD MESSAGES FROM GOOGLE SHEET ===\n",
    "def load_messages_from_sheet():\n",
    "    \"\"\"Loads message text and image URLs from the specified Google Sheet.\"\"\"\n",
    "    global all_messages\n",
    "    global current_message_index\n",
    "    try:\n",
    "        df = pd.read_csv(SHEET_CSV_URL, on_bad_lines='skip')\n",
    "        messages = []\n",
    "        for _, row in df.iterrows():\n",
    "            text = str(row['Text']).strip()\n",
    "            raw_url = str(row['ImageURL']).strip() if 'ImageURL' in row and pd.notna(row['ImageURL']) else None\n",
    "            image_url = convert_drive_link(raw_url)\n",
    "            if text:\n",
    "                messages.append((text, image_url))\n",
    "\n",
    "        if not messages:\n",
    "            logger.warning(\"No messages found in sheet! Bot will not send messages.\")\n",
    "            all_messages = []\n",
    "        else:\n",
    "            # Check if messages have changed significantly to avoid unnecessary index reset\n",
    "            if all_messages and len(messages) == len(all_messages) and all(messages[i] == all_messages[i] for i in range(len(messages))):\n",
    "                logger.info(\"Messages from sheet are unchanged. Keeping current_message_index.\")\n",
    "            else:\n",
    "                current_message_index = 0 # Reset index when loading new or changed messages\n",
    "                logger.info(\"Messages from sheet have changed or are new. Resetting current_message_index to 0.\")\n",
    "\n",
    "            all_messages = messages\n",
    "            logger.info(f\"Successfully loaded {len(all_messages)} messages from Google Sheet.\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logger.error(f\"❌ Failed to read Google Sheet: {e}\")\n",
    "        all_messages = [] # Clear messages on failure to prevent using old data\n",
    "\n",
    "# === TELEGRAM INTERACTION: SEND MESSAGE TO TELEGRAM ===\n",
    "async def send_telegram_message(text, image_url=None):\n",
    "    \"\"\"Sends a text message or photo with caption to the configured channel.\"\"\"\n",
    "    url = f\"https://api.telegram.org/bot{BOT_TOKEN}\"\n",
    "    try:\n",
    "        if image_url and image_url.startswith(\"http\"):\n",
    "            response = requests.post(f\"{url}/sendPhoto\", data={\n",
    "                'chat_id': CHANNEL_ID,\n",
    "                'caption': text,\n",
    "                'photo': image_url\n",
    "            })\n",
    "        else:\n",
    "            response = requests.post(f\"{url}/sendMessage\", data={\n",
    "                'chat_id': CHANNEL_ID,\n",
    "                'text': text\n",
    "            })\n",
    "        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)\n",
    "        logger.info(f\"✅ Sent message to channel. Status: {response.status_code}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        logger.error(f\"❌ Telegram send error: {e}\")\n",
    "    except Exception as e:\n",
    "        logger.error(f\"❌ Unexpected error sending message: {e}\")\n",
    "\n",
    "# === SCHEDULER CALLBACK: FUNCTION TO BE CALLED BY APSCHEDULER ===\n",
    "async def send_scheduled_message_from_sheet():\n",
    "    \"\"\"Retrieves the next message from the loaded list and sends it.\"\"\"\n",
    "    global current_message_index\n",
    "    if not all_messages:\n",
    "        logger.warning(\"No messages loaded to send. Attempting to reload messages from sheet.\")\n",
    "        load_messages_from_sheet() # Try to reload messages immediately before sending\n",
    "        if not all_messages: # If still no messages after reload\n",
    "            logger.error(\"Still no messages after reload. Skipping sending this time.\")\n",
    "            return\n",
    "\n",
    "    try:\n",
    "        text, image_url = all_messages[current_message_index]\n",
    "        await send_telegram_message(text, image_url)\n",
    "        current_message_index = (current_message_index + 1) % len(all_messages)\n",
    "    except IndexError:\n",
    "        logger.error(\"Message index out of bounds. This shouldn't happen with modulo arithmetic. Resetting index to 0.\")\n",
    "        current_message_index = 0\n",
    "    except Exception as e:\n",
    "        logger.error(f\"Error preparing or sending scheduled message: {e}\")\n",
    "\n",
    "# === TELEGRAM BOT COMMAND HANDLERS ===\n",
    "async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:\n",
    "    \"\"\"Sends a welcome message and explains the bot's purpose.\"\"\"\n",
    "    user = update.effective_user\n",
    "    scheduled_times_str = \", \".join([f\"{h:02d}:{m:02d}\" for h, m in SCHEDULED_TIMES_MOSCOW])\n",
    "    await update.message.reply_html(\n",
    "        f\"Hi {user.mention_html()}! I am a bot designed to send daily messages \"\n",
    "        f\"at the following Moscow times: **{scheduled_times_str}** to the configured channel.\\n\"\n",
    "        f\"I also reload messages from the Google Sheet every **{SHEET_RELOAD_INTERVAL_HOURS} hours**.\\n\"\n",
    "        \"Use /check_messages to manually reload messages.\\n\"\n",
    "        \"Use /current_index to see which message will be sent next.\"\n",
    "    )\n",
    "\n",
    "async def check_messages(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:\n",
    "    \"\"\"Command to manually check and reload messages from the Google Sheet.\"\"\"\n",
    "    await update.message.reply_text(\"Attempting to reload messages from the Google Sheet...\")\n",
    "    load_messages_from_sheet()\n",
    "    if all_messages:\n",
    "        await update.message.reply_text(f\"Successfully reloaded **{len(all_messages)}** messages.\")\n",
    "    else:\n",
    "        await update.message.reply_text(\"Failed to reload messages or no messages found. Check bot logs for errors.\")\n",
    "\n",
    "async def current_index(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:\n",
    "    \"\"\"Command to show the current message index.\"\"\"\n",
    "    if all_messages:\n",
    "        await update.message.reply_text(\n",
    "            f\"Currently, the bot will send message number **{current_message_index + 1}** \"\n",
    "            f\"out of **{len(all_messages)}** total messages.\"\n",
    "        )\n",
    "    else:\n",
    "        await update.message.reply_text(\"No messages are currently loaded.\")\n",
    "\n",
    "# === MAIN FUNCTION: BOT STARTUP AND SCHEDULING ===\n",
    "async def main() -> None:\n",
    "    \"\"\"Starts the bot, loads initial messages, and sets up scheduled jobs.\"\"\"\n",
    "    # Load messages initially when the bot starts\n",
    "    load_messages_from_sheet()\n",
    "\n",
    "    # Create the Telegram Application instance with your bot's token\n",
    "    application = Application.builder().token(BOT_TOKEN).build()\n",
    "\n",
    "    # Initialize APScheduler for asynchronous tasks\n",
    "    scheduler = AsyncIOScheduler()\n",
    "\n",
    "    # Add jobs for each specified time to send messages\n",
    "    for hour, minute in SCHEDULED_TIMES_MOSCOW:\n",
    "        job_id = f'daily_message_{hour:02d}_{minute:02d}'\n",
    "        scheduler.add_job(\n",
    "            send_scheduled_message_from_sheet,\n",
    "            CronTrigger(hour=hour, minute=minute, timezone=MOSCOW_TIMEZONE),\n",
    "            id=job_id,\n",
    "            name=f'Send message at {hour:02d}:{minute:02d} Moscow time'\n",
    "        )\n",
    "        logger.info(f\"Scheduled job: {job_id} for {hour:02d}:{minute:02d} {MOSCOW_TIMEZONE}\")\n",
    "\n",
    "    # NEW JOB: Schedule periodic reloading of messages from Google Sheet\n",
    "    scheduler.add_job(\n",
    "        load_messages_from_sheet,\n",
    "        IntervalTrigger(hours=SHEET_RELOAD_INTERVAL_HOURS),\n",
    "        id='reload_sheet_messages',\n",
    "        name=f'Reload messages from Google Sheet every {SHEET_RELOAD_INTERVAL_HOURS} hours'\n",
    "    )\n",
    "    logger.info(f\"Scheduled job: reload_sheet_messages every {SHEET_RELOAD_INTERVAL_HOURS} hours.\")\n",
    "\n",
    "    # Start the scheduler. Jobs will run automatically at their designated times.\n",
    "    scheduler.start()\n",
    "\n",
    "    # Add command handlers to the Telegram Application\n",
    "    application.add_handler(CommandHandler(\"start\", start))\n",
    "    application.add_handler(CommandHandler(\"check_messages\", check_messages))\n",
    "    application.add_handler(CommandHandler(\"current_index\", current_index))\n",
    "\n",
    "    logger.info(\"Bot started. Press Ctrl+C to stop.\")\n",
    "    await application.start_polling(allowed_updates=Update.ALL_TYPES, close_loop=False)\n",
    "\n",
    "    # Cleanly shut down the scheduler when the bot stops (e.g., via Ctrl+C or kernel stop)\n",
    "    scheduler.shutdown()\n",
    "    logger.info(\"Bot stopped.\")\n",
    "\n",
    "# === ENTRY POINT ===\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        loop = asyncio.get_running_loop()\n",
    "    except RuntimeError: # No loop is running.\n",
    "        loop = None\n",
    "\n",
    "    if loop and loop.is_running():\n",
    "        # If a loop is already running (e.g., in Jupyter),\n",
    "        # schedule main as a task on the existing loop.\n",
    "        asyncio.create_task(main())\n",
    "        logger.info(\"Bot main function scheduled as a task on existing event loop.\")\n",
    "    else:\n",
    "        # If no loop is running (e.g., running as a standalone script from terminal),\n",
    "        # create and run a new loop to execute main.\n",
    "        asyncio.run(main())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e8337b79-f03c-4be6-9fa9-25c9cbfd7e94",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
